name: moldynstudio
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.11
  - pip
  - gromacs
  - ambertools=23
  - gmx_mmpbsa
  - mdanalysis
  - mdtraj<1.11
  - prody
  - matplotlib
  - seaborn
  - numpy>=1.26,<2
  - pandas
  - scipy
  - openpyxl
  - pip:
      - py3dmol
      - acpype
