from __future__ import annotations

import tempfile
import threading
import unittest
from dataclasses import replace
from pathlib import Path
from types import SimpleNamespace
from unittest import mock

from core import gromacs_runner
from core.artifact_validation import ValidationResult
from core.gromacs_capabilities import GPU_MODE_AUTO, GromacsCapabilities
from core.md_pipeline import build_pipeline, build_production_stage
from core.md_pipeline_runner import (
    ArtifactValidators,
    CommandOutcome,
    MDPipelineRunner,
    MDPipelineService,
    PipelineResumeError,
)
from core.run_manifest import (
    StageName,
    StageStatus,
    load_manifest,
    new_manifest,
    save_manifest,
)
from core.stage_qc import QCCheck, QCSeverity, StageQCResult


def _valid_gro() -> str:
    return (
        "Generated by test\n"
        "1\n"
        "    1SOL     OW    1   0.000   0.000   0.000\n"
        "1.0 1.0 1.0\n"
    )


def _capabilities() -> GromacsCapabilities:
    return GromacsCapabilities(
        executable="gmx",
        version_text="GROMACS version: 2026.3",
        version="2026.3",
        executable_ok=True,
        gpu_support_text=None,
        hardware_notes=(),
        mdrun_help_text="-nt -nb -pme -bonded -update",
    )


def _validators() -> ArtifactValidators:
    def present(path: str | Path) -> ValidationResult:
        candidate = Path(path)
        return ValidationResult(candidate.is_file(), f"checked {candidate.name}")

    return ArtifactValidators(
        validate_gro=present,
        validate_tpr=present,
        validate_checkpoint=present,
        validate_file=present,
    )


def _manifest(root: Path) -> Path:
    (root / "system.gro").write_text(_valid_gro(), encoding="utf-8")
    (root / "topol.top").write_text(
        "[ system ]\nTest system\n[ molecules ]\nProtein 1\n",
        encoding="utf-8",
    )
    (root / "em.mdp").write_text(
        "integrator = steep\nnsteps = 50000\n", encoding="utf-8",
    )
    for filename in ("nvt.mdp", "npt.mdp", "md.mdp"):
        (root / filename).write_text(
            "integrator = md\nnsteps = 50000\ndt = 0.002\n",
            encoding="utf-8",
        )
    manifest = new_manifest(
        root,
        "protein",
        "protein.pdb",
        None,
        "amber99sb",
        "tip3p",
        "gmx",
        "moldynstudio",
        4,
        GPU_MODE_AUTO,
    )
    stages = dict(manifest.stages)
    stages[StageName.PREPARATION.value] = replace(
        stages[StageName.PREPARATION.value],
        status=StageStatus.COMPLETED.value,
    )
    stages[StageName.MINIMIZATION.value] = replace(
        stages[StageName.MINIMIZATION.value],
        status=StageStatus.READY.value,
    )
    path = root / "moldynstudio_run.json"
    save_manifest(replace(manifest, stages=stages), path)
    return path


class FakeCommandRunner:
    def __init__(
        self,
        root: Path,
        *,
        fail: tuple[str, str] | None = None,
        omit: str | None = None,
    ) -> None:
        self.root = root
        self.fail = fail
        self.omit = omit
        self.commands = []
        self.cancelled = False

    def execute(self, command, on_output=None) -> CommandOutcome:
        self.commands.append(command)
        subcommand = command.args[0]
        if self.fail == (command.stage, subcommand):
            return CommandOutcome(2)
        if subcommand == "grompp":
            output = command.args[command.args.index("-o") + 1]
            self._write(output, "tpr")
        elif subcommand == "mdrun":
            stem = command.args[command.args.index("-deffnm") + 1]
            self._write(f"{stem}.gro", _valid_gro())
            self._write(f"{stem}.cpt", "checkpoint")
            self._write(f"{stem}.log", "log")
            self._write(f"{stem}.edr", "energy")
            self._write(f"{stem}.xtc", "trajectory")
        if on_output is not None:
            on_output(f"ran {command.stage} {subcommand}")
        return CommandOutcome(0)

    def cancel_active(self) -> None:
        self.cancelled = True

    def _write(self, name: str, content: str) -> None:
        if name != self.omit:
            (self.root / name).write_text(content, encoding="utf-8")


class BlockingProductionRunner(FakeCommandRunner):
    def __init__(self, root: Path) -> None:
        super().__init__(root)
        self.production_started = threading.Event()
        self.release = threading.Event()

    def execute(self, command, on_output=None) -> CommandOutcome:
        if command.stage == StageName.PRODUCTION.value and command.args[0] == "mdrun":
            self.commands.append(command)
            self.production_started.set()
            self.release.wait(timeout=3)
            return CommandOutcome(-1, cancelled=True)
        return super().execute(command, on_output)

    def cancel_active(self) -> None:
        super().cancel_active()
        self.release.set()


class MDPipelineServiceTests(unittest.TestCase):
    def test_preflight_failure_blocks_external_commands_and_fails_stage(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            path = _manifest(root)
            (root / "em.mdp").unlink()
            runner = FakeCommandRunner(root)
            service = MDPipelineService(
                path,
                build_pipeline(root, (StageName.MINIMIZATION,)),
                _capabilities(),
                command_runner=runner,
                validators=_validators(),
            )

            self.assertFalse(service.run())

            self.assertEqual(runner.commands, [])
            stage = load_manifest(path).stages[StageName.MINIMIZATION.value]
            self.assertEqual(stage.status, StageStatus.FAILED.value)
            self.assertIn("preflight", stage.message.lower())
            self.assertIn("em.mdp", stage.message)

    def test_preflight_warning_is_logged_and_does_not_block_commands(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            path = _manifest(root)
            runner = FakeCommandRunner(root)
            logs = []
            service = MDPipelineService(
                path,
                build_pipeline(root, (StageName.MINIMIZATION,)),
                _capabilities(),
                command_runner=runner,
                validators=_validators(),
                on_log=logs.append,
                free_space_warning_bytes=10**30,
            )

            self.assertTrue(service.run())

            self.assertTrue(runner.commands)
            self.assertTrue(any("preflight warning" in line.lower() for line in logs))

    def test_happy_path_emits_stage_sequence_and_completes_manifest(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            path = _manifest(root)
            runner = FakeCommandRunner(root)
            transitions = []
            completions = []
            service = MDPipelineService(
                path,
                build_pipeline(
                    root,
                    (
                        StageName.MINIMIZATION,
                        StageName.NVT,
                        StageName.NPT,
                        StageName.PRODUCTION,
                    ),
                ),
                _capabilities(),
                command_runner=runner,
                validators=_validators(),
                on_stage_status=lambda name, status, _message: transitions.append(
                    (name, status)
                ),
                on_finished=lambda success, message: completions.append((success, message)),
            )

            self.assertTrue(service.run())

            self.assertEqual(
                transitions,
                [
                    (StageName.MINIMIZATION, StageStatus.RUNNING),
                    (StageName.MINIMIZATION, StageStatus.COMPLETED),
                    (StageName.NVT, StageStatus.RUNNING),
                    (StageName.NVT, StageStatus.COMPLETED),
                    (StageName.NPT, StageStatus.RUNNING),
                    (StageName.NPT, StageStatus.COMPLETED),
                    (StageName.PRODUCTION, StageStatus.RUNNING),
                    (StageName.PRODUCTION, StageStatus.COMPLETED),
                ],
            )
            self.assertEqual(completions, [(True, "MD pipeline completed.")])
            manifest = load_manifest(path)
            for name in (
                StageName.MINIMIZATION,
                StageName.NVT,
                StageName.NPT,
                StageName.PRODUCTION,
            ):
                self.assertEqual(
                    manifest.stages[name.value].status,
                    StageStatus.COMPLETED.value,
                )

    def test_grompp_failure_marks_stage_failed_and_dependents_not_ready(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            path = _manifest(root)
            runner = FakeCommandRunner(root, fail=(StageName.NVT.value, "grompp"))
            service = MDPipelineService(
                path,
                build_pipeline(root),
                _capabilities(),
                command_runner=runner,
                validators=_validators(),
            )

            self.assertFalse(service.run())

            manifest = load_manifest(path)
            self.assertEqual(
                manifest.stages[StageName.MINIMIZATION.value].status,
                StageStatus.COMPLETED.value,
            )
            self.assertEqual(
                manifest.stages[StageName.NVT.value].status,
                StageStatus.FAILED.value,
            )
            for name in (StageName.NPT, StageName.PRODUCTION):
                self.assertEqual(
                    manifest.stages[name.value].status,
                    StageStatus.NOT_READY.value,
                )
            self.assertFalse(
                any(command.stage == StageName.NPT.value for command in runner.commands)
            )

    def test_zero_mdrun_with_missing_structure_fails_output_validation(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            path = _manifest(root)
            runner = FakeCommandRunner(root, omit="nvt.gro")
            service = MDPipelineService(
                path,
                build_pipeline(root),
                _capabilities(),
                command_runner=runner,
                validators=_validators(),
            )

            self.assertFalse(service.run())

            manifest = load_manifest(path)
            self.assertEqual(
                manifest.stages[StageName.NVT.value].status,
                StageStatus.FAILED.value,
            )
            self.assertNotEqual(
                manifest.stages[StageName.NVT.value].status,
                StageStatus.COMPLETED.value,
            )

    def test_every_required_mdrun_artifact_gates_stage_completion(self):
        required_outputs = {
            StageName.MINIMIZATION: ("em.gro", "em.edr", "em.log"),
            StageName.NVT: ("nvt.gro", "nvt.edr", "nvt.log", "nvt.cpt"),
            StageName.NPT: ("npt.gro", "npt.edr", "npt.log", "npt.cpt"),
            StageName.PRODUCTION: (
                "md.gro",
                "md.edr",
                "md.log",
                "md.cpt",
                "md.xtc",
            ),
        }
        for expected_stage, filenames in required_outputs.items():
            for missing in filenames:
                with self.subTest(stage=expected_stage.value, missing=missing):
                    with tempfile.TemporaryDirectory() as directory:
                        root = Path(directory)
                        path = _manifest(root)
                        service = MDPipelineService(
                            path,
                            build_pipeline(root),
                            _capabilities(),
                            command_runner=FakeCommandRunner(root, omit=missing),
                            validators=_validators(),
                        )

                        self.assertFalse(service.run())

                        stage = load_manifest(path).stages[expected_stage.value]
                        self.assertEqual(stage.status, StageStatus.FAILED.value)
                        self.assertIn(missing, stage.message)

    def test_executor_exception_is_persisted_as_failure(self):
        class RaisingRunner(FakeCommandRunner):
            def execute(self, command, on_output=None) -> CommandOutcome:
                raise OSError("runner unavailable")

        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            path = _manifest(root)
            service = MDPipelineService(
                path,
                build_pipeline(root, (StageName.MINIMIZATION,)),
                _capabilities(),
                command_runner=RaisingRunner(root),
                validators=_validators(),
            )

            self.assertFalse(service.run())

            stage = load_manifest(path).stages[StageName.MINIMIZATION.value]
            self.assertEqual(stage.status, StageStatus.FAILED.value)
            self.assertIn("runner unavailable", stage.message)

    def test_stop_cancels_active_production_and_never_completes_it(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            path = _manifest(root)
            runner = BlockingProductionRunner(root)
            service = MDPipelineService(
                path,
                build_pipeline(root),
                _capabilities(),
                command_runner=runner,
                validators=_validators(),
            )
            worker = threading.Thread(target=service.run)
            worker.start()
            self.assertTrue(runner.production_started.wait(timeout=3))

            service.stop()
            worker.join(timeout=3)

            self.assertFalse(worker.is_alive())
            self.assertTrue(runner.cancelled)
            self.assertEqual(
                load_manifest(path).stages[StageName.PRODUCTION.value].status,
                StageStatus.STOPPED.value,
            )

    def test_resume_validates_checkpoint_and_adds_resource_arguments(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            path = _manifest(root)
            for filename in ("md.tpr", "md.cpt", "md.log", "md.edr"):
                (root / filename).write_text(filename, encoding="utf-8")
            runner = FakeCommandRunner(root)
            service = MDPipelineService(
                path,
                (build_production_stage(root),),
                _capabilities(),
                command_runner=runner,
                validators=_validators(),
            )

            with mock.patch("core.gromacs_capabilities.os.cpu_count", return_value=8):
                self.assertTrue(service.resume_production())

            self.assertEqual(len(runner.commands), 1)
            self.assertEqual(
                runner.commands[0].args,
                (
                    "mdrun",
                    "-deffnm",
                    "md",
                    "-cpi",
                    "md.cpt",
                    "-v",
                    "-nt",
                    "4",
                ),
            )

    def test_windows_resume_reaches_wsl_bridge_with_tokens_cwd_and_conda_env(self):
        windows_project = r"C:\Users\Test User\MolDynStudio Project"
        configured_env = "configured-md-env"
        process = mock.Mock()
        process.pid = 1001
        process.poll.return_value = None
        process.stdout = iter(
            [f"{gromacs_runner.WSL_PGID_PREFIX}1001\n", "Finished mdrun\n"]
        )
        process.wait.return_value = 0
        process.stdin = mock.Mock()

        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            path = _manifest(root)
            manifest = load_manifest(path)
            save_manifest(
                replace(
                    manifest,
                    project_dir=windows_project,
                    conda_environment=configured_env,
                ),
                path,
            )

            def always_valid(candidate):
                return ValidationResult(
                    True, f"mocked validation for {candidate}"
                )

            service = MDPipelineService(
                path,
                (build_production_stage(windows_project),),
                _capabilities(),
                validators=ArtifactValidators(
                    validate_gro=always_valid,
                    validate_tpr=always_valid,
                    validate_checkpoint=always_valid,
                    validate_file=always_valid,
                ),
            )

            with (
                mock.patch.object(
                    gromacs_runner, "os", SimpleNamespace(name="nt")
                ),
                mock.patch.object(
                    gromacs_runner.shutil, "which", return_value="wsl.exe"
                ),
                mock.patch.object(
                    gromacs_runner.wsl_bridge, "IS_WINDOWS", True
                ),
                mock.patch.object(
                    gromacs_runner.wsl_bridge.subprocess,
                    "Popen",
                    return_value=process,
                ) as process_launch,
                mock.patch(
                    "core.gromacs_capabilities.os.cpu_count", return_value=8
                ),
            ):
                self.assertTrue(service.resume_production())

        process_launch.assert_called_once()
        wrapped_command = process_launch.call_args.args[0]
        self.assertEqual(
            wrapped_command[:4], ["wsl.exe", "--", "bash", "-lc"]
        )
        script = wrapped_command[4]
        self.assertIn(
            "cd '/mnt/c/Users/Test User/MolDynStudio Project' &&",
            script,
        )
        self.assertIn(f"conda run --no-capture-output -n {configured_env}", script)
        self.assertIn(
            "gmx mdrun -deffnm md -cpi md.cpt -v",
            script,
        )
        self.assertIn(r"moldynstudio_pgid=\$!", script)
        self.assertNotIn(windows_project, script)

    def test_resume_rejects_any_invalid_checkpoint_input_before_launch(self):
        required = ("md.tpr", "md.cpt", "md.log", "md.edr")
        for missing in required:
            with self.subTest(missing=missing):
                with tempfile.TemporaryDirectory() as directory:
                    root = Path(directory)
                    path = _manifest(root)
                    for filename in required:
                        if filename != missing:
                            (root / filename).write_text(filename, encoding="utf-8")
                    runner = FakeCommandRunner(root)
                    service = MDPipelineService(
                        path,
                        (build_production_stage(root),),
                        _capabilities(),
                        command_runner=runner,
                        validators=_validators(),
                    )

                    with self.assertRaisesRegex(PipelineResumeError, missing):
                        service.resume_production()

                    self.assertEqual(runner.commands, [])

    def test_qc_runs_after_artifact_validation_and_is_persisted_before_completed(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            path = _manifest(root)
            validated: set[str] = set()
            completed_payloads = []

            def present(candidate: str | Path) -> ValidationResult:
                artifact = Path(candidate)
                if artifact.is_file():
                    validated.add(artifact.name)
                return ValidationResult(artifact.is_file(), f"checked {artifact.name}")

            validators = ArtifactValidators(
                validate_gro=present,
                validate_tpr=present,
                validate_checkpoint=present,
                validate_file=present,
            )

            def evaluate(stage: StageName, outputs: dict[str, str]) -> StageQCResult:
                required = {"em.gro", "em.edr", "em.log"}
                self.assertTrue(required <= validated)
                self.assertTrue(required <= outputs.keys())
                self.assertEqual(
                    load_manifest(path).stages[stage.value].status,
                    StageStatus.RUNNING.value,
                )
                return StageQCResult(
                    stage.value,
                    (
                        QCCheck(
                            "temperature",
                            QCSeverity.WARNING,
                            "Temperature diagnostics are optional in minimization.",
                            outputs["em.log"],
                            {},
                        ),
                    ),
                )

            def on_status(
                stage: StageName,
                status: StageStatus,
                _message: str,
            ) -> None:
                if status == StageStatus.COMPLETED:
                    completed_payloads.append(
                        load_manifest(path).metadata["stage_qc"][stage.value]
                    )

            service = MDPipelineService(
                path,
                build_pipeline(root, (StageName.MINIMIZATION,)),
                _capabilities(),
                command_runner=FakeCommandRunner(root),
                validators=validators,
                stage_qc_evaluator=evaluate,
                on_stage_status=on_status,
            )

            self.assertTrue(service.run())

            self.assertEqual(len(completed_payloads), 1)
            self.assertEqual(completed_payloads[0]["outcome"], "warning")
            stage = load_manifest(path).stages[StageName.MINIMIZATION.value]
            self.assertEqual(stage.status, StageStatus.COMPLETED.value)
            self.assertIn("QC warning", stage.message)

    def test_artifact_failure_skips_qc_and_never_completes(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            path = _manifest(root)
            evaluations = []

            def evaluate(stage, outputs):
                evaluations.append((stage, outputs))
                return StageQCResult(stage.value, ())

            service = MDPipelineService(
                path,
                build_pipeline(root, (StageName.MINIMIZATION,)),
                _capabilities(),
                command_runner=FakeCommandRunner(root, omit="em.log"),
                validators=_validators(),
                stage_qc_evaluator=evaluate,
            )

            self.assertFalse(service.run())

            manifest = load_manifest(path)
            self.assertEqual(evaluations, [])
            self.assertNotIn(
                StageName.MINIMIZATION.value,
                manifest.metadata.get("stage_qc", {}),
            )
            self.assertEqual(
                manifest.stages[StageName.MINIMIZATION.value].status,
                StageStatus.FAILED.value,
            )

    def test_qc_warning_logs_and_preserves_unrelated_manifest_metadata(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            path = _manifest(root)
            manifest = load_manifest(path)
            save_manifest(
                replace(
                    manifest,
                    metadata={
                        "owner": "scientist",
                        "stage_qc": {
                            "external": {"outcome": "passed", "checks": []}
                        },
                    },
                ),
                path,
            )
            logs = []

            def evaluate(stage, outputs):
                return StageQCResult(
                    stage.value,
                    (
                        QCCheck(
                            "pressure",
                            QCSeverity.WARNING,
                            "Pressure magnitude is high.",
                            outputs["em.log"],
                            {"maximum": 5000.0},
                        ),
                    ),
                )

            service = MDPipelineService(
                path,
                build_pipeline(root, (StageName.MINIMIZATION,)),
                _capabilities(),
                command_runner=FakeCommandRunner(root),
                validators=_validators(),
                stage_qc_evaluator=evaluate,
                on_log=logs.append,
            )

            self.assertTrue(service.run())

            persisted = load_manifest(path)
            self.assertEqual(persisted.metadata["owner"], "scientist")
            self.assertEqual(
                persisted.metadata["stage_qc"]["external"]["outcome"],
                "passed",
            )
            self.assertEqual(
                persisted.metadata["stage_qc"]["minimization"]["outcome"],
                "warning",
            )
            self.assertTrue(any(line.startswith("QC warning (minimization)") for line in logs))

    def test_explicit_fatal_qc_fails_stage_and_invalidates_downstream(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            path = _manifest(root)
            manifest = load_manifest(path)
            save_manifest(
                replace(
                    manifest,
                    metadata={
                        "stage_qc": {
                            "nvt": {"outcome": "warning", "checks": []},
                            "npt": {"outcome": "passed", "checks": []},
                        }
                    },
                ),
                path,
            )
            transitions = []

            def evaluate(stage, outputs):
                return StageQCResult(
                    stage.value,
                    (
                        QCCheck(
                            "temperature",
                            QCSeverity.FATAL,
                            "Required temperature diagnostics are malformed.",
                            outputs["em.log"],
                            {},
                        ),
                    ),
                )

            service = MDPipelineService(
                path,
                build_pipeline(root),
                _capabilities(),
                command_runner=FakeCommandRunner(root),
                validators=_validators(),
                stage_qc_evaluator=evaluate,
                on_stage_status=lambda stage, status, _message: transitions.append(
                    (stage, status)
                ),
            )

            self.assertFalse(service.run())

            manifest = load_manifest(path)
            self.assertEqual(
                manifest.metadata["stage_qc"]["minimization"]["outcome"],
                "fatal",
            )
            self.assertNotIn("nvt", manifest.metadata["stage_qc"])
            self.assertNotIn("npt", manifest.metadata["stage_qc"])
            self.assertEqual(
                manifest.stages[StageName.MINIMIZATION.value].status,
                StageStatus.FAILED.value,
            )
            self.assertNotIn(
                (StageName.MINIMIZATION, StageStatus.COMPLETED),
                transitions,
            )
            for stage in (StageName.NVT, StageName.NPT, StageName.PRODUCTION):
                self.assertEqual(
                    manifest.stages[stage.value].status,
                    StageStatus.NOT_READY.value,
                )


class MDPipelineThreadTests(unittest.TestCase):
    def test_qt_wrapper_forwards_stage_and_completion_signals(self):
        class FakeService:
            def __init__(self) -> None:
                self.on_stage_status = None
                self.on_log = None
                self.on_finished = None
                self.stopped = False

            def run(self) -> bool:
                self.on_stage_status(
                    StageName.NVT, StageStatus.RUNNING, "NVT is running."
                )
                self.on_log("Step 1")
                self.on_finished(True, "done")
                return True

            def stop(self) -> None:
                self.stopped = True

        service = FakeService()
        thread = MDPipelineRunner(service=service)
        stages = []
        logs = []
        finished = []
        thread.stage_changed.connect(lambda *values: stages.append(values))
        thread.log_line.connect(logs.append)
        thread.finished_with_status.connect(lambda *values: finished.append(values))

        thread.run()
        thread.stop()

        self.assertEqual(stages, [("nvt", "running", "NVT is running.")])
        self.assertEqual(logs, ["Step 1"])
        self.assertEqual(finished, [(True, "done")])
        self.assertTrue(service.stopped)


if __name__ == "__main__":
    unittest.main()
