from __future__ import annotations

import tempfile
import threading
import unittest
from dataclasses import replace
from pathlib import Path
from unittest import mock

from core.artifact_validation import ValidationResult
from core.gromacs_capabilities import GPU_MODE_AUTO, GromacsCapabilities
from core.md_pipeline import build_pipeline, build_production_stage
from core.md_pipeline_runner import (
    ArtifactValidators,
    CommandOutcome,
    MDPipelineRunner,
    MDPipelineService,
    PipelineResumeError,
)
from core.run_manifest import (
    StageName,
    StageStatus,
    load_manifest,
    new_manifest,
    save_manifest,
)


def _valid_gro() -> str:
    return (
        "Generated by test\n"
        "1\n"
        "    1SOL     OW    1   0.000   0.000   0.000\n"
        "1.0 1.0 1.0\n"
    )


def _capabilities() -> GromacsCapabilities:
    return GromacsCapabilities(
        executable="gmx",
        version_text="GROMACS version: 2026.3",
        version="2026.3",
        executable_ok=True,
        gpu_support_text=None,
        hardware_notes=(),
        mdrun_help_text="-nt -nb -pme -bonded -update",
    )


def _validators() -> ArtifactValidators:
    def present(path: str | Path) -> ValidationResult:
        candidate = Path(path)
        return ValidationResult(candidate.is_file(), f"checked {candidate.name}")

    return ArtifactValidators(
        validate_gro=present,
        validate_tpr=present,
        validate_checkpoint=present,
        validate_file=present,
    )


def _manifest(root: Path) -> Path:
    manifest = new_manifest(
        root,
        "protein",
        "protein.pdb",
        None,
        "amber99sb",
        "tip3p",
        "gmx",
        "moldynstudio",
        4,
        GPU_MODE_AUTO,
    )
    stages = dict(manifest.stages)
    stages[StageName.PREPARATION.value] = replace(
        stages[StageName.PREPARATION.value],
        status=StageStatus.COMPLETED.value,
    )
    stages[StageName.MINIMIZATION.value] = replace(
        stages[StageName.MINIMIZATION.value],
        status=StageStatus.READY.value,
    )
    path = root / "moldynstudio_run.json"
    save_manifest(replace(manifest, stages=stages), path)
    return path


class FakeCommandRunner:
    def __init__(
        self,
        root: Path,
        *,
        fail: tuple[str, str] | None = None,
        omit: str | None = None,
    ) -> None:
        self.root = root
        self.fail = fail
        self.omit = omit
        self.commands = []
        self.cancelled = False

    def execute(self, command, on_output=None) -> CommandOutcome:
        self.commands.append(command)
        subcommand = command.args[0]
        if self.fail == (command.stage, subcommand):
            return CommandOutcome(2)
        if subcommand == "grompp":
            output = command.args[command.args.index("-o") + 1]
            self._write(output, "tpr")
        elif subcommand == "mdrun":
            stem = command.args[command.args.index("-deffnm") + 1]
            self._write(f"{stem}.gro", _valid_gro())
            self._write(f"{stem}.cpt", "checkpoint")
            self._write(f"{stem}.log", "log")
            self._write(f"{stem}.edr", "energy")
            self._write(f"{stem}.xtc", "trajectory")
        if on_output is not None:
            on_output(f"ran {command.stage} {subcommand}")
        return CommandOutcome(0)

    def cancel_active(self) -> None:
        self.cancelled = True

    def _write(self, name: str, content: str) -> None:
        if name != self.omit:
            (self.root / name).write_text(content, encoding="utf-8")


class BlockingProductionRunner(FakeCommandRunner):
    def __init__(self, root: Path) -> None:
        super().__init__(root)
        self.production_started = threading.Event()
        self.release = threading.Event()

    def execute(self, command, on_output=None) -> CommandOutcome:
        if command.stage == StageName.PRODUCTION.value and command.args[0] == "mdrun":
            self.commands.append(command)
            self.production_started.set()
            self.release.wait(timeout=3)
            return CommandOutcome(-1, cancelled=True)
        return super().execute(command, on_output)

    def cancel_active(self) -> None:
        super().cancel_active()
        self.release.set()


class MDPipelineServiceTests(unittest.TestCase):
    def test_happy_path_emits_stage_sequence_and_completes_manifest(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            path = _manifest(root)
            runner = FakeCommandRunner(root)
            transitions = []
            completions = []
            service = MDPipelineService(
                path,
                build_pipeline(
                    root,
                    (
                        StageName.MINIMIZATION,
                        StageName.NVT,
                        StageName.NPT,
                        StageName.PRODUCTION,
                    ),
                ),
                _capabilities(),
                command_runner=runner,
                validators=_validators(),
                on_stage_status=lambda name, status, _message: transitions.append(
                    (name, status)
                ),
                on_finished=lambda success, message: completions.append((success, message)),
            )

            self.assertTrue(service.run())

            self.assertEqual(
                transitions,
                [
                    (StageName.MINIMIZATION, StageStatus.RUNNING),
                    (StageName.MINIMIZATION, StageStatus.COMPLETED),
                    (StageName.NVT, StageStatus.RUNNING),
                    (StageName.NVT, StageStatus.COMPLETED),
                    (StageName.NPT, StageStatus.RUNNING),
                    (StageName.NPT, StageStatus.COMPLETED),
                    (StageName.PRODUCTION, StageStatus.RUNNING),
                    (StageName.PRODUCTION, StageStatus.COMPLETED),
                ],
            )
            self.assertEqual(completions, [(True, "MD pipeline completed.")])
            manifest = load_manifest(path)
            for name in (
                StageName.MINIMIZATION,
                StageName.NVT,
                StageName.NPT,
                StageName.PRODUCTION,
            ):
                self.assertEqual(
                    manifest.stages[name.value].status,
                    StageStatus.COMPLETED.value,
                )

    def test_grompp_failure_marks_stage_failed_and_dependents_not_ready(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            path = _manifest(root)
            runner = FakeCommandRunner(root, fail=(StageName.NVT.value, "grompp"))
            service = MDPipelineService(
                path,
                build_pipeline(root),
                _capabilities(),
                command_runner=runner,
                validators=_validators(),
            )

            self.assertFalse(service.run())

            manifest = load_manifest(path)
            self.assertEqual(
                manifest.stages[StageName.MINIMIZATION.value].status,
                StageStatus.COMPLETED.value,
            )
            self.assertEqual(
                manifest.stages[StageName.NVT.value].status,
                StageStatus.FAILED.value,
            )
            for name in (StageName.NPT, StageName.PRODUCTION):
                self.assertEqual(
                    manifest.stages[name.value].status,
                    StageStatus.NOT_READY.value,
                )
            self.assertFalse(
                any(command.stage == StageName.NPT.value for command in runner.commands)
            )

    def test_zero_mdrun_with_missing_structure_fails_output_validation(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            path = _manifest(root)
            runner = FakeCommandRunner(root, omit="nvt.gro")
            service = MDPipelineService(
                path,
                build_pipeline(root),
                _capabilities(),
                command_runner=runner,
                validators=_validators(),
            )

            self.assertFalse(service.run())

            manifest = load_manifest(path)
            self.assertEqual(
                manifest.stages[StageName.NVT.value].status,
                StageStatus.FAILED.value,
            )
            self.assertNotEqual(
                manifest.stages[StageName.NVT.value].status,
                StageStatus.COMPLETED.value,
            )

    def test_every_required_mdrun_artifact_gates_stage_completion(self):
        required_outputs = {
            StageName.MINIMIZATION: ("em.gro", "em.edr", "em.log"),
            StageName.NVT: ("nvt.gro", "nvt.edr", "nvt.log", "nvt.cpt"),
            StageName.NPT: ("npt.gro", "npt.edr", "npt.log", "npt.cpt"),
            StageName.PRODUCTION: (
                "md.gro",
                "md.edr",
                "md.log",
                "md.cpt",
                "md.xtc",
            ),
        }
        for expected_stage, filenames in required_outputs.items():
            for missing in filenames:
                with self.subTest(stage=expected_stage.value, missing=missing):
                    with tempfile.TemporaryDirectory() as directory:
                        root = Path(directory)
                        path = _manifest(root)
                        service = MDPipelineService(
                            path,
                            build_pipeline(root),
                            _capabilities(),
                            command_runner=FakeCommandRunner(root, omit=missing),
                            validators=_validators(),
                        )

                        self.assertFalse(service.run())

                        stage = load_manifest(path).stages[expected_stage.value]
                        self.assertEqual(stage.status, StageStatus.FAILED.value)
                        self.assertIn(missing, stage.message)

    def test_executor_exception_is_persisted_as_failure(self):
        class RaisingRunner(FakeCommandRunner):
            def execute(self, command, on_output=None) -> CommandOutcome:
                raise OSError("runner unavailable")

        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            path = _manifest(root)
            service = MDPipelineService(
                path,
                build_pipeline(root, (StageName.MINIMIZATION,)),
                _capabilities(),
                command_runner=RaisingRunner(root),
                validators=_validators(),
            )

            self.assertFalse(service.run())

            stage = load_manifest(path).stages[StageName.MINIMIZATION.value]
            self.assertEqual(stage.status, StageStatus.FAILED.value)
            self.assertIn("runner unavailable", stage.message)

    def test_stop_cancels_active_production_and_never_completes_it(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            path = _manifest(root)
            runner = BlockingProductionRunner(root)
            service = MDPipelineService(
                path,
                build_pipeline(root),
                _capabilities(),
                command_runner=runner,
                validators=_validators(),
            )
            worker = threading.Thread(target=service.run)
            worker.start()
            self.assertTrue(runner.production_started.wait(timeout=3))

            service.stop()
            worker.join(timeout=3)

            self.assertFalse(worker.is_alive())
            self.assertTrue(runner.cancelled)
            self.assertEqual(
                load_manifest(path).stages[StageName.PRODUCTION.value].status,
                StageStatus.STOPPED.value,
            )

    def test_resume_validates_checkpoint_and_adds_resource_arguments(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            path = _manifest(root)
            for filename in ("md.tpr", "md.cpt", "md.log", "md.edr"):
                (root / filename).write_text(filename, encoding="utf-8")
            runner = FakeCommandRunner(root)
            service = MDPipelineService(
                path,
                (build_production_stage(root),),
                _capabilities(),
                command_runner=runner,
                validators=_validators(),
            )

            with mock.patch("core.gromacs_capabilities.os.cpu_count", return_value=8):
                self.assertTrue(service.resume_production())

            self.assertEqual(len(runner.commands), 1)
            self.assertEqual(
                runner.commands[0].args,
                (
                    "mdrun",
                    "-deffnm",
                    "md",
                    "-cpi",
                    "md.cpt",
                    "-v",
                    "-nt",
                    "4",
                ),
            )

    def test_resume_rejects_any_invalid_checkpoint_input_before_launch(self):
        required = ("md.tpr", "md.cpt", "md.log", "md.edr")
        for missing in required:
            with self.subTest(missing=missing):
                with tempfile.TemporaryDirectory() as directory:
                    root = Path(directory)
                    path = _manifest(root)
                    for filename in required:
                        if filename != missing:
                            (root / filename).write_text(filename, encoding="utf-8")
                    runner = FakeCommandRunner(root)
                    service = MDPipelineService(
                        path,
                        (build_production_stage(root),),
                        _capabilities(),
                        command_runner=runner,
                        validators=_validators(),
                    )

                    with self.assertRaisesRegex(PipelineResumeError, missing):
                        service.resume_production()

                    self.assertEqual(runner.commands, [])


class MDPipelineThreadTests(unittest.TestCase):
    def test_qt_wrapper_forwards_stage_and_completion_signals(self):
        class FakeService:
            def __init__(self) -> None:
                self.on_stage_status = None
                self.on_log = None
                self.on_finished = None
                self.stopped = False

            def run(self) -> bool:
                self.on_stage_status(
                    StageName.NVT, StageStatus.RUNNING, "NVT is running."
                )
                self.on_log("Step 1")
                self.on_finished(True, "done")
                return True

            def stop(self) -> None:
                self.stopped = True

        service = FakeService()
        thread = MDPipelineRunner(service=service)
        stages = []
        logs = []
        finished = []
        thread.stage_changed.connect(lambda *values: stages.append(values))
        thread.log_line.connect(logs.append)
        thread.finished_with_status.connect(lambda *values: finished.append(values))

        thread.run()
        thread.stop()

        self.assertEqual(stages, [("nvt", "running", "NVT is running.")])
        self.assertEqual(logs, ["Step 1"])
        self.assertEqual(finished, [(True, "done")])
        self.assertTrue(service.stopped)


if __name__ == "__main__":
    unittest.main()
