from __future__ import annotations

import tempfile
import unittest
from pathlib import Path

from analysis.qc import (
    compare_replicates,
    parse_numeric_series,
    summarize_series,
)


class QCAnalysisTests(unittest.TestCase):
    def test_parse_xvg_ignores_comments_and_reads_columns(self):
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "rmsd.xvg"
            path.write_text(
                "# generated by gmx rms\n"
                "@ title \"RMSD\"\n"
                "0.0 0.10\n"
                "1.0 0.12\n",
                encoding="utf-8",
            )

            series = parse_numeric_series(path)

        self.assertEqual(series.metric, "RMSD")
        self.assertEqual(series.time, (0.0, 1.0))
        self.assertEqual(series.values, (0.10, 0.12))

    def test_summarize_series_detects_equilibration_after_initial_ramp(self):
        time = tuple(float(i) for i in range(30))
        values = tuple([2.0, 1.6, 1.2, 0.9, 0.6] + [0.42 + (0.01 if i % 2 else 0.0) for i in range(25)])

        summary = summarize_series("RMSD", time, values)

        self.assertEqual(summary.status, "OK")
        self.assertIsNotNone(summary.burn_in_time)
        self.assertGreater(summary.burn_in_time or 0.0, 0.0)

    def test_summarize_series_warns_on_late_drift(self):
        time = tuple(float(i) for i in range(40))
        values = tuple(0.2 + i * 0.02 for i in range(40))

        summary = summarize_series("RMSD", time, values)

        self.assertEqual(summary.status, "WARN")
        self.assertIn("drift", summary.message.lower())

    def test_compare_replicates_flags_large_spread(self):
        summaries = (
            summarize_series("RMSD", tuple(range(20)), tuple([0.2] * 20), replicate="rep1"),
            summarize_series("RMSD", tuple(range(20)), tuple([0.8] * 20), replicate="rep2"),
        )

        comparison = compare_replicates(summaries)

        self.assertEqual(comparison.status, "WARN")
        self.assertIn("spread", comparison.message.lower())

    def test_rmsf_is_treated_as_distribution_not_burn_in_series(self):
        summary = summarize_series("RMSF", tuple(range(10)), tuple([0.1, 0.2, 0.4, 0.2, 0.1] * 2))

        self.assertEqual(summary.status, "OK")
        self.assertIsNone(summary.burn_in_time)
        self.assertIn("distribution", summary.message.lower())


if __name__ == "__main__":
    unittest.main()
