from __future__ import annotations

import unittest
import tempfile
from dataclasses import replace
from pathlib import Path
from types import SimpleNamespace

from core.gromacs_capabilities import (
    GPU_MODE_AUTO,
    GPU_MODE_SUPPORTED,
    GromacsCapabilities,
)
from core.md_pipeline import (
    DEFAULT_FREE_SPACE_WARNING_BYTES,
    PipelineCommand,
    PipelineStage,
    build_minimize_stage,
    build_npt_stage,
    build_nvt_stage,
    build_pipeline,
    build_prepare_stage,
    build_production_stage,
    preflight_stage,
)
from core.run_manifest import StageName, StageStatus, new_manifest


VALID_GRO = (
    "Generated by test\n"
    "1\n"
    "    1SOL     OW    1   0.000   0.000   0.000\n"
    "1.0 1.0 1.0\n"
)


def _capabilities(*, executable_ok: bool = True, gpu: str | None = None) -> GromacsCapabilities:
    return GromacsCapabilities(
        executable="gmx",
        version_text="GROMACS version: 2026.3",
        version="2026.3",
        executable_ok=executable_ok,
        gpu_support_text=gpu,
        hardware_notes=(),
        mdrun_help_text="-nt -nb -pme -bonded -update",
    )


def _manifest(root: Path):
    manifest = new_manifest(
        root, "protein", "protein.pdb", None, "amber99sb", "tip3p",
        "gmx", "moldynstudio", 4, GPU_MODE_AUTO,
    )
    stages = dict(manifest.stages)
    for name in StageName:
        stages[name.value] = replace(
            stages[name.value], status=StageStatus.COMPLETED.value,
        )
    return replace(manifest, stages=stages)


def _write_inputs(root: Path) -> None:
    for name in ("system.gro", "em.gro", "nvt.gro", "npt.gro"):
        (root / name).write_text(VALID_GRO, encoding="utf-8")
    (root / "topol.top").write_text(
        "[ system ]\nTest system\n[ molecules ]\nProtein 1\n",
        encoding="utf-8",
    )
    (root / "em.mdp").write_text("integrator = steep\nnsteps = 50000\n", encoding="utf-8")
    for name in ("nvt.mdp", "npt.mdp", "md.mdp"):
        (root / name).write_text(
            "integrator = md\nnsteps = 50000\ndt = 0.002\n",
            encoding="utf-8",
        )
    for name in ("nvt.cpt", "npt.cpt"):
        (root / name).write_bytes(b"checkpoint")


def _preflight(stage, manifest, **kwargs):
    return preflight_stage(
        stage,
        manifest,
        manifest.conda_environment,
        manifest.gromacs_binary,
        capabilities=_capabilities(),
        writable_probe=lambda _root: True,
        disk_usage=lambda _root: SimpleNamespace(free=DEFAULT_FREE_SPACE_WARNING_BYTES * 2),
        **kwargs,
    )


class MDPipelineTests(unittest.TestCase):
    def test_commands_are_tokenized_and_use_project_as_cwd(self):
        stage = build_nvt_stage("/tmp/project")
        self.assertIsInstance(stage, PipelineStage)
        self.assertEqual(stage.commands[0].args, (
            "grompp", "-f", "nvt.mdp", "-c", "em.gro", "-r", "em.gro",
            "-p", "topol.top", "-o", "nvt.tpr",
        ))
        self.assertEqual(stage.commands[0].cwd, "/tmp/project")
        self.assertIsInstance(stage.commands[0], PipelineCommand)

    def test_stage_commands_use_expected_artifacts(self):
        self.assertEqual(build_prepare_stage("p").commands, ())
        self.assertEqual(build_minimize_stage("p").commands[0].args, (
            "grompp", "-f", "em.mdp", "-c", "system.gro", "-p",
            "topol.top", "-o", "em.tpr",
        ))
        self.assertEqual(build_minimize_stage("p").commands[1].args,
                         ("mdrun", "-deffnm", "em"))
        self.assertEqual(build_npt_stage("p").commands[0].args, (
            "grompp", "-f", "npt.mdp", "-c", "nvt.gro", "-r", "nvt.gro",
            "-t", "nvt.cpt", "-p", "topol.top", "-o", "npt.tpr",
        ))
        self.assertEqual(build_nvt_stage("p").commands[1].args,
                         ("mdrun", "-deffnm", "nvt"))
        self.assertEqual(build_npt_stage("p").commands[1].args,
                         ("mdrun", "-deffnm", "npt"))
        self.assertEqual(build_production_stage("p").commands[0].args, (
            "grompp", "-f", "md.mdp", "-c", "npt.gro", "-t", "npt.cpt",
            "-p", "topol.top", "-o", "md.tpr",
        ))
        self.assertEqual(build_production_stage("p").commands[1].args,
                         ("mdrun", "-deffnm", "md"))

    def test_pipeline_has_canonical_dependency_order_and_resume_slice(self):
        all_stages = build_pipeline("p", tuple(StageName))
        self.assertEqual(tuple(stage.name for stage in all_stages), tuple(StageName))
        resumed = build_pipeline("p", tuple(StageName),
                                 resume_from_stage=StageName.NPT)
        self.assertEqual(tuple(stage.name for stage in resumed),
                         (StageName.NPT, StageName.PRODUCTION))
        resumed_alias = build_pipeline("p", tuple(StageName),
                                       resume_from=StageName.NPT)
        self.assertEqual(tuple(stage.name for stage in resumed_alias),
                         (StageName.NPT, StageName.PRODUCTION))

    def test_pipeline_does_not_reorder_selected_stages_or_add_maxwarn(self):
        stages = build_pipeline("p", (StageName.MINIMIZATION, StageName.NVT,
                                       StageName.NPT, StageName.PRODUCTION))
        self.assertEqual(tuple(stage.name for stage in stages),
                         (StageName.MINIMIZATION, StageName.NVT,
                          StageName.NPT, StageName.PRODUCTION))
        for stage in stages:
            for command in stage.commands:
                self.assertNotIn("-maxwarn", command.args)

    def test_preflight_accepts_each_stage_with_valid_scientific_inputs(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            _write_inputs(root)
            manifest = _manifest(root)
            for stage in build_pipeline(root, (
                StageName.MINIMIZATION, StageName.NVT,
                StageName.NPT, StageName.PRODUCTION,
            )):
                with self.subTest(stage=stage.name.value):
                    result = _preflight(stage, manifest)
                    self.assertTrue(result.ok, result.message)
                    self.assertEqual(result.warnings, ())

    def test_preflight_fails_closed_for_every_required_stage_input(self):
        cases = {
            StageName.MINIMIZATION: ("system.gro", "topol.top", "em.mdp"),
            StageName.NVT: ("em.gro", "topol.top", "nvt.mdp"),
            StageName.NPT: ("nvt.gro", "nvt.cpt", "topol.top", "npt.mdp"),
            StageName.PRODUCTION: ("npt.gro", "npt.cpt", "topol.top", "md.mdp"),
        }
        for stage_name, filenames in cases.items():
            for missing in filenames:
                with self.subTest(stage=stage_name.value, missing=missing):
                    with tempfile.TemporaryDirectory() as directory:
                        root = Path(directory)
                        _write_inputs(root)
                        (root / missing).unlink()
                        stage = build_pipeline(root, (stage_name,))[0]
                        result = _preflight(stage, _manifest(root))
                        self.assertFalse(result.ok)
                        self.assertIn(missing, result.message)

    def test_preflight_requires_nvt_restraint_reference_to_be_exactly_em_gro(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            _write_inputs(root)
            stage = build_nvt_stage(root)
            bad_args = tuple(
                "system.gro" if value == "em.gro" and index == stage.commands[0].args.index("-r") + 1 else value
                for index, value in enumerate(stage.commands[0].args)
            )
            bad_stage = PipelineStage(
                StageName.NVT,
                (replace(stage.commands[0], args=bad_args), *stage.commands[1:]),
            )
            result = _preflight(bad_stage, _manifest(root))
        self.assertFalse(result.ok)
        self.assertIn("restraint", result.message.lower())
        self.assertIn("em.gro", result.message)

    def test_preflight_separates_low_space_warning_from_fatal_blockers(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            _write_inputs(root)
            manifest = _manifest(root)
            result = preflight_stage(
                build_minimize_stage(root), manifest,
                manifest.conda_environment, manifest.gromacs_binary,
                capabilities=_capabilities(), writable_probe=lambda _root: True,
                disk_usage=lambda _root: SimpleNamespace(free=1024),
                free_space_warning_bytes=4096,
            )
        self.assertTrue(result.ok, result.message)
        self.assertEqual(len(result.warnings), 1)
        self.assertIn("free space", result.warnings[0].lower())

    def test_preflight_rejects_unwritable_project_bad_resources_and_missing_prerequisite(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            _write_inputs(root)
            manifest = _manifest(root)
            stage = build_npt_stage(root)

            unwritable = preflight_stage(
                stage, manifest, "env", "gmx", capabilities=_capabilities(),
                writable_probe=lambda _root: False,
                disk_usage=lambda _root: SimpleNamespace(free=10**12),
            )
            self.assertFalse(unwritable.ok)
            self.assertIn("writable", unwritable.message.lower())

            bad_cores = _preflight(stage, replace(manifest, requested_cores=0))
            self.assertFalse(bad_cores.ok)
            self.assertIn("core", bad_cores.message.lower())

            no_gromacs = preflight_stage(
                stage, manifest, "env", "gmx",
                capabilities=_capabilities(executable_ok=False),
                writable_probe=lambda _root: True,
                disk_usage=lambda _root: SimpleNamespace(free=10**12),
            )
            self.assertFalse(no_gromacs.ok)
            self.assertIn("callable", no_gromacs.message.lower())

            gpu_manifest = replace(manifest, gpu_mode=GPU_MODE_SUPPORTED)
            no_gpu = _preflight(stage, gpu_manifest)
            self.assertFalse(no_gpu.ok)
            self.assertIn("gpu", no_gpu.message.lower())

            stages = dict(manifest.stages)
            stages[StageName.NVT.value] = replace(
                stages[StageName.NVT.value], status=StageStatus.NOT_READY.value,
            )
            missing_prerequisite = _preflight(
                stage, replace(manifest, stages=stages),
            )
            self.assertFalse(missing_prerequisite.ok)
            self.assertIn("prerequisite", missing_prerequisite.message.lower())

    def test_preflight_checks_ligand_itp_name_against_topology(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            _write_inputs(root)
            ligand_dir = root / "ligand"
            ligand_dir.mkdir()
            ligand_itp = ligand_dir / "ligand.itp"
            ligand_itp.write_text("[ moleculetype ]\nLIG 3\n", encoding="utf-8")
            manifest = replace(
                _manifest(root),
                system_kind="protein_ligand",
                ligand_source="ligand.sdf",
            )
            preparation = replace(
                manifest.stages[StageName.PREPARATION.value],
                outputs={"ligand/ligand.itp": str(ligand_itp)},
            )
            manifest = replace(
                manifest,
                stages={**manifest.stages, StageName.PREPARATION.value: preparation},
            )
            result = _preflight(build_minimize_stage(root), manifest)
            self.assertFalse(result.ok)
            self.assertIn("LIG", result.message)

            (root / "topol.top").write_text(
                "[ system ]\nComplex\n[ molecules ]\nProtein 1\nLIG 1\n",
                encoding="utf-8",
            )
            self.assertTrue(
                _preflight(build_minimize_stage(root), manifest).ok,
            )


if __name__ == "__main__":
    unittest.main()
