from __future__ import annotations

import tempfile
import unittest
from dataclasses import replace
from pathlib import Path
from unittest import mock

from core.preparation_orchestrator import (
    CommandResult,
    PreparationCommandBuilder,
    PreparationError,
    PreparationOrchestrator,
    PreparationRequest,
)
from core.run_manifest import (
    CommandRecord,
    StageName,
    StageStatus,
    load_manifest,
    new_manifest,
    save_manifest,
)
from core.system_prep import SystemPrepParams
from utils.mdp_generator import MDParameters
from utils.topology_builder import LigandTopologyArtifacts


GRO_TEXT = (
    "Generated by test\n"
    "1\n"
    "    1PRO     CA    1   0.000   0.000   0.000\n"
    "   1.00000   1.00000   1.00000\n"
)
TOP_TEXT = "[ system ]\nTest system\n[ molecules ]\nProtein 1\n"


class MaterializingRunner:
    def __init__(self, fail_on: str | None = None, omit_final: bool = False):
        self.commands = []
        self.fail_on = fail_on
        self.omit_final = omit_final

    def run(self, command, on_output=None):
        self.commands.append(command)
        executable = Path(command.argv[0]).name
        subcommand = command.argv[1] if executable != "acpype" else "acpype"
        if on_output:
            on_output(f"running {subcommand}")
        if subcommand == self.fail_on:
            return CommandResult(2, "", f"{subcommand} failed")
        cwd = Path(command.cwd)
        if subcommand == "pdb2gmx":
            (cwd / "protein.gro").write_text(GRO_TEXT, encoding="utf-8")
            (cwd / "topol.top").write_text(TOP_TEXT, encoding="utf-8")
        elif subcommand == "editconf":
            (cwd / "boxed.gro").write_text(GRO_TEXT, encoding="utf-8")
        elif subcommand == "solvate":
            (cwd / "solvated.gro").write_text(GRO_TEXT, encoding="utf-8")
        elif subcommand == "grompp":
            (cwd / "ions.tpr").write_bytes(b"tpr")
        elif subcommand == "genion" and not self.omit_final:
            (cwd / "system.gro").write_text(GRO_TEXT, encoding="utf-8")
        return CommandResult(0, f"completed {subcommand}", "")


def request(root: Path, ligand: str | None = None) -> PreparationRequest:
    protein = root / "protein.pdb"
    protein.write_text("ATOM\n", encoding="utf-8")
    if ligand:
        (root / ligand).write_text("ligand\n", encoding="utf-8")
    return PreparationRequest(
        system=SystemPrepParams(
            pdb_path=str(protein),
            work_dir=str(root),
            force_field="AMBER99SB-ILDN",
        ),
        ligand_path=str(root / ligand) if ligand else None,
        md_parameters=MDParameters(duration_ns=1.0),
        gromacs_binary="auto",
        conda_environment="md-env",
        requested_cores=6,
        gpu_mode="CPU only",
    )


class PreparationOrchestratorTests(unittest.TestCase):
    def test_protein_only_sequence_uses_configured_binary_and_environment(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            runner = MaterializingRunner()
            service = PreparationOrchestrator(
                request(root),
                runner=runner,
                structure_validator=lambda _path: None,
            )

            result = service.run()

            self.assertEqual(
                [command.argv[1] for command in runner.commands],
                ["pdb2gmx", "editconf", "solvate", "grompp", "genion"],
            )
            self.assertTrue(
                all(command.argv[0] == "gmx" for command in runner.commands)
            )
            self.assertTrue(all(command.conda_environment == "md-env" for command in runner.commands))
            self.assertEqual(runner.commands[-1].stdin_text, "SOL\n")
            self.assertEqual(result.system_gro, (root / "system.gro").resolve())

    def test_protein_ligand_sequence_normalizes_combines_and_patches_before_boxing(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            runner = MaterializingRunner()
            ligand_dir = root / "ligand"
            ligand_dir.mkdir()
            ligand_gro = ligand_dir / "ligand.gro"
            ligand_itp = ligand_dir / "ligand.itp"
            ligand_gro.write_text(GRO_TEXT, encoding="utf-8")
            ligand_itp.write_text("[ moleculetype ]\nMOL 3\n", encoding="utf-8")
            artifacts = LigandTopologyArtifacts(ligand_gro, ligand_itp)
            events = []

            def combine(protein, ligand, output):
                events.append(("combine", Path(protein).name, Path(ligand).name))
                Path(output).write_text(GRO_TEXT, encoding="utf-8")
                return Path(output)

            def patch(topology, itp, **_kwargs):
                events.append(("patch", Path(topology).name, Path(itp).name))
                Path(topology).write_text(
                    "[ system ]\nTest system\n[ molecules ]\nProtein 1\nMOL 1\n",
                    encoding="utf-8",
                )
                return Path(topology)

            service = PreparationOrchestrator(
                request(root, "ligand.sdf"),
                runner=runner,
                structure_validator=lambda _path: None,
                ligand_normalizer=lambda _source, _project: artifacts,
                gro_combiner=combine,
                topology_patcher=patch,
            )

            service.run()

            self.assertEqual(
                [command.argv[1] if command.argv[0] != "acpype" else "acpype" for command in runner.commands],
                ["pdb2gmx", "acpype", "editconf", "solvate", "grompp", "genion"],
            )
            self.assertEqual(events, [("combine", "protein.gro", "ligand.gro"), ("patch", "topol.top", "ligand.itp")])
            editconf = runner.commands[2]
            self.assertEqual(editconf.argv[editconf.argv.index("-f") + 1], "complex.gro")

    def test_success_writes_mdps_and_completes_manifest_after_validation(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            service = PreparationOrchestrator(
                request(root),
                runner=MaterializingRunner(),
                structure_validator=lambda _path: None,
            )

            service.run()

            manifest = load_manifest(root / "moldynstudio_run.json")
            preparation = manifest.stages["preparation"]
            self.assertEqual(preparation.status, StageStatus.COMPLETED.value)
            self.assertEqual(manifest.stages["minimization"].status, StageStatus.READY.value)
            expected = {"system.gro", "topol.top", "em.mdp", "nvt.mdp", "npt.mdp", "md.mdp"}
            self.assertTrue(expected.issubset(preparation.outputs))
            for filename in expected:
                self.assertEqual(preparation.outputs[filename], str((root / filename).resolve()))
                self.assertTrue((root / filename).is_file())

    def test_command_failure_marks_preparation_failed_and_minimization_not_ready(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            service = PreparationOrchestrator(
                request(root),
                runner=MaterializingRunner(fail_on="solvate"),
                structure_validator=lambda _path: None,
            )

            with self.assertRaisesRegex(PreparationError, "solvate failed"):
                service.run()

            manifest = load_manifest(root / "moldynstudio_run.json")
            self.assertEqual(manifest.stages["preparation"].status, StageStatus.FAILED.value)
            self.assertEqual(manifest.stages["minimization"].status, StageStatus.NOT_READY.value)

    def test_missing_final_artifact_never_marks_completed(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            service = PreparationOrchestrator(
                request(root),
                runner=MaterializingRunner(omit_final=True),
                structure_validator=lambda _path: None,
            )

            with self.assertRaisesRegex(PreparationError, "system.gro"):
                service.run()

            manifest = load_manifest(root / "moldynstudio_run.json")
            self.assertEqual(manifest.stages["preparation"].status, StageStatus.FAILED.value)
            self.assertNotEqual(manifest.stages["minimization"].status, StageStatus.READY.value)

    def test_command_builder_never_hardcodes_gmx(self):
        with (
            mock.patch(
                "core.gromacs_capabilities.wsl_bridge.IS_WINDOWS", True
            ),
            mock.patch(
                "core.gromacs_capabilities.wsl_bridge.win_to_wsl",
                return_value="/mnt/c/tools/gmx-custom",
            ) as translate,
        ):
            builder = PreparationCommandBuilder(r"C:\tools\gmx-custom", "custom-env")
        command = builder.gromacs("genion", ["-s", "ions.tpr"], "project", stdin_text="SOL\n")

        translate.assert_called_once_with(r"C:\tools\gmx-custom")
        self.assertEqual(command.argv[:2], ("/mnt/c/tools/gmx-custom", "genion"))
        self.assertEqual(command.conda_environment, "custom-env")

    def test_command_builder_accepts_valid_explicit_linux_path(self):
        with tempfile.TemporaryDirectory() as tmp:
            executable = Path(tmp) / "gmx-custom"
            executable.touch()
            executable.chmod(0o755)
            with mock.patch(
                "core.gromacs_capabilities.wsl_bridge.IS_WINDOWS", False
            ):
                builder = PreparationCommandBuilder(str(executable), "research")

        self.assertEqual(builder.gromacs_binary, str(executable))
        self.assertEqual(builder.conda_environment, "research")

    def test_command_builder_resolves_auto_before_building_commands(self):
        with mock.patch(
            "core.preparation_orchestrator.resolve_gromacs_binary",
            return_value="gmx",
        ) as resolve:
            builder = PreparationCommandBuilder("Auto", "research")

        self.assertEqual(builder.gromacs_binary, "gmx")
        self.assertEqual(builder.conda_environment, "research")
        resolve.assert_called_once_with("Auto")

    def test_command_builder_rejects_missing_binary_before_any_command(self):
        with (
            mock.patch(
                "core.gromacs_capabilities.wsl_bridge.IS_WINDOWS", False
            ),
            self.assertRaisesRegex(FileNotFoundError, "GROMACS executable not found"),
        ):
            PreparationCommandBuilder("/missing/gmx", "research")

    def test_rerun_failure_invalidates_every_completed_downstream_stage(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            rerun_request = request(root)
            manifest = new_manifest(
                root,
                "protein",
                rerun_request.system.pdb_path,
                None,
                rerun_request.system.force_field,
                rerun_request.system.water_model,
                rerun_request.gromacs_binary,
                rerun_request.conda_environment,
                rerun_request.requested_cores,
                rerun_request.gpu_mode,
            )
            old_command = CommandRecord(
                "production", ["old-gmx", "mdrun"], str(root), "old-start"
            )
            for stage_name in (
                StageName.MINIMIZATION,
                StageName.NVT,
                StageName.NPT,
                StageName.PRODUCTION,
            ):
                stage = manifest.stages[stage_name.value]
                command = replace(old_command, stage=stage_name.value)
                manifest.stages[stage_name.value] = replace(
                    stage,
                    status=StageStatus.COMPLETED.value,
                    started_at="old-start",
                    finished_at="old-finish",
                    message="Old run completed.",
                    commands=[command],
                    inputs={"old-input": "obsolete.gro"},
                    outputs={"old-output": "obsolete.cpt"},
                )
            save_manifest(manifest, root / "moldynstudio_run.json")

            running_snapshot = []

            class SnapshotRunner(MaterializingRunner):
                def run(self, command, on_output=None):
                    if not running_snapshot:
                        running_snapshot.append(
                            load_manifest(root / "moldynstudio_run.json")
                        )
                    return super().run(command, on_output)

            service = PreparationOrchestrator(
                rerun_request,
                runner=SnapshotRunner(fail_on="solvate"),
                structure_validator=lambda _path: None,
            )

            with self.assertRaises(PreparationError):
                service.run()

            self.assertEqual(
                running_snapshot[0].stages["preparation"].status,
                StageStatus.RUNNING.value,
            )
            failed_manifest = load_manifest(root / "moldynstudio_run.json")
            self.assertEqual(
                failed_manifest.stages["preparation"].status,
                StageStatus.FAILED.value,
            )
            for candidate in (running_snapshot[0], failed_manifest):
                for stage_name in (
                    StageName.MINIMIZATION,
                    StageName.NVT,
                    StageName.NPT,
                    StageName.PRODUCTION,
                ):
                    stage = candidate.stages[stage_name.value]
                    self.assertEqual(stage.status, StageStatus.NOT_READY.value)
                    self.assertIsNone(stage.started_at)
                    self.assertIsNone(stage.finished_at)
                    self.assertEqual(stage.commands, [])
                    self.assertEqual(stage.inputs, {})
                    self.assertEqual(stage.outputs, {})
                    self.assertIn("preparation", stage.message.lower())


if __name__ == "__main__":
    unittest.main()
