from __future__ import annotations

import os
import tempfile
import unittest
from dataclasses import replace
from pathlib import Path

os.environ.setdefault("QT_QPA_PLATFORM", "offscreen")
os.environ.setdefault("QTWEBENGINE_DISABLE_SANDBOX", "1")

from PyQt5.QtWidgets import QApplication, QLabel

from core.artifact_validation import ValidationResult
from core.gromacs_capabilities import GromacsCapabilities
from core.md_pipeline_runner import ArtifactValidators
from core.run_manifest import (
    StageName,
    StageStatus,
    load_manifest,
    new_manifest,
    save_manifest,
)
from tabs.md_run_tab import MDRunTab


GRO_TEXT = (
    "Generated by test\n"
    "1\n"
    "    1SOL     OW    1   0.000   0.000   0.000\n"
    "   1.00000   1.00000   1.00000\n"
)


class FakeSignal:
    def __init__(self) -> None:
        self._callbacks = []

    def connect(self, callback, *_args, **_kwargs) -> None:
        self._callbacks.append(callback)

    def emit(self, *args, **kwargs) -> None:
        for callback in tuple(self._callbacks):
            callback(*args, **kwargs)


class FakeRunner:
    def __init__(self, manifest_file, stages, capabilities, *, resume=False) -> None:
        self.manifest_file = Path(manifest_file)
        self.stages = tuple(stages)
        self.capabilities = capabilities
        self.resume = resume
        self.started = False
        self.stopped = False
        self.stage_changed = FakeSignal()
        self.log_line = FakeSignal()
        self.finished_with_status = FakeSignal()

    def start(self) -> None:
        self.started = True

    def stop(self) -> None:
        self.stopped = True


def _capabilities() -> GromacsCapabilities:
    return GromacsCapabilities(
        executable="gmx",
        version_text="GROMACS version: 2026.3",
        version="2026.3",
        executable_ok=True,
        gpu_support_text=None,
        hardware_notes=(),
        mdrun_help_text="-nt -nb -pme -bonded -update",
    )


def _validators() -> ArtifactValidators:
    def present(path: str | Path) -> ValidationResult:
        candidate = Path(path)
        return ValidationResult(candidate.is_file(), f"checked {candidate.name}")

    return ArtifactValidators(
        validate_gro=present,
        validate_tpr=present,
        validate_checkpoint=present,
        validate_file=present,
    )


def _manifest(root: Path) -> Path:
    manifest = new_manifest(
        root,
        "protein",
        "protein.pdb",
        None,
        "amber99sb",
        "tip3p",
        "gmx",
        "moldynstudio",
        4,
        "Auto",
    )
    for filename in ("system.gro", "topol.top", "em.mdp", "nvt.mdp", "npt.mdp", "md.mdp"):
        content = GRO_TEXT if filename.endswith(".gro") else "placeholder\n"
        (root / filename).write_text(content, encoding="utf-8")
    preparation = replace(
        manifest.stages[StageName.PREPARATION.value],
        status=StageStatus.COMPLETED.value,
        outputs={
            "system.gro": str((root / "system.gro").resolve()),
            "topol.top": str((root / "topol.top").resolve()),
            "em.mdp": str((root / "em.mdp").resolve()),
            "nvt.mdp": str((root / "nvt.mdp").resolve()),
            "npt.mdp": str((root / "npt.mdp").resolve()),
            "md.mdp": str((root / "md.mdp").resolve()),
        },
    )
    stages = dict(manifest.stages)
    stages[StageName.PREPARATION.value] = preparation
    stages[StageName.MINIMIZATION.value] = replace(
        stages[StageName.MINIMIZATION.value],
        status=StageStatus.READY.value,
    )
    path = root / "moldynstudio_run.json"
    save_manifest(replace(manifest, stages=stages), path)
    return path


def _set_stage_status(
    root: Path,
    stage: StageName,
    status: StageStatus,
    outputs: dict[str, str] | None = None,
) -> None:
    path = root / "moldynstudio_run.json"
    manifest = load_manifest(path)
    stages = {
        **manifest.stages,
        stage.value: replace(
            manifest.stages[stage.value],
            status=status.value,
            outputs=outputs or {},
        ),
    }
    save_manifest(replace(manifest, stages=stages), path)


class MDRunTabTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.app = QApplication.instance() or QApplication([])

    def test_run_button_starts_real_runner_from_manifest_context(self):
        created = []

        def factory(manifest_file, stages, capabilities, *, resume=False):
            runner = FakeRunner(
                manifest_file,
                stages,
                capabilities,
                resume=resume,
            )
            created.append(runner)
            return runner

        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            _manifest(root)
            tab = MDRunTab(
                runner_factory=factory,
                capability_probe=lambda _exe, _env: _capabilities(),
                artifact_validators=_validators(),
            )
            self.addCleanup(tab.deleteLater)

            tab.load_project(str(root))
            tab.run_button.click()

            self.assertEqual(len(created), 1)
            runner = created[0]
            self.assertTrue(runner.started)
            self.assertFalse(runner.resume)
            self.assertEqual(runner.manifest_file, root / "moldynstudio_run.json")
            self.assertEqual(
                [stage.name for stage in runner.stages],
                [
                    StageName.MINIMIZATION,
                    StageName.NVT,
                    StageName.NPT,
                    StageName.PRODUCTION,
                ],
            )

    def test_selector_enables_only_scientifically_possible_restart_points(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            _manifest(root)
            tab = MDRunTab(
                runner_factory=lambda *args, **kwargs: FakeRunner(*args, **kwargs),
                capability_probe=lambda _exe, _env: _capabilities(),
                artifact_validators=_validators(),
            )
            self.addCleanup(tab.deleteLater)
            tab.load_project(str(root))

            self.assertTrue(tab.resume_selector.model().item(0).isEnabled())
            self.assertFalse(tab.resume_selector.model().item(1).isEnabled())
            self.assertFalse(tab.resume_selector.model().item(2).isEnabled())
            self.assertFalse(tab.resume_selector.model().item(3).isEnabled())
            self.assertFalse(tab.resume_selector.model().item(4).isEnabled())

            (root / "em.gro").write_text(GRO_TEXT, encoding="utf-8")
            _set_stage_status(
                root,
                StageName.MINIMIZATION,
                StageStatus.COMPLETED,
                {"em.gro": str((root / "em.gro").resolve())},
            )
            tab.refresh_from_manifest()
            self.assertTrue(tab.resume_selector.model().item(1).isEnabled())

            (root / "nvt.gro").write_text(GRO_TEXT, encoding="utf-8")
            (root / "nvt.cpt").write_text("checkpoint", encoding="utf-8")
            _set_stage_status(
                root,
                StageName.NVT,
                StageStatus.COMPLETED,
                {
                    "nvt.gro": str((root / "nvt.gro").resolve()),
                    "nvt.cpt": str((root / "nvt.cpt").resolve()),
                },
            )
            tab.refresh_from_manifest()
            self.assertTrue(tab.resume_selector.model().item(2).isEnabled())

            (root / "npt.gro").write_text(GRO_TEXT, encoding="utf-8")
            (root / "npt.cpt").write_text("checkpoint", encoding="utf-8")
            _set_stage_status(
                root,
                StageName.NPT,
                StageStatus.COMPLETED,
                {
                    "npt.gro": str((root / "npt.gro").resolve()),
                    "npt.cpt": str((root / "npt.cpt").resolve()),
                },
            )
            tab.refresh_from_manifest()
            self.assertTrue(tab.resume_selector.model().item(3).isEnabled())

            (root / "md.tpr").write_text("tpr", encoding="utf-8")
            (root / "md.cpt").write_text("checkpoint", encoding="utf-8")
            _set_stage_status(root, StageName.PRODUCTION, StageStatus.INTERRUPTED)
            tab.refresh_from_manifest()
            self.assertTrue(tab.resume_selector.model().item(4).isEnabled())

    def test_resume_selector_requires_both_structure_and_checkpoint(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            _manifest(root)
            tab = MDRunTab(
                runner_factory=lambda *args, **kwargs: FakeRunner(*args, **kwargs),
                capability_probe=lambda _exe, _env: _capabilities(),
                artifact_validators=_validators(),
            )
            self.addCleanup(tab.deleteLater)
            tab.load_project(str(root))

            (root / "nvt.gro").write_text(GRO_TEXT, encoding="utf-8")
            tab.refresh_from_manifest()
            self.assertFalse(tab.resume_selector.model().item(2).isEnabled())

            (root / "nvt.gro").unlink()
            (root / "nvt.cpt").write_text("checkpoint", encoding="utf-8")
            tab.refresh_from_manifest()
            self.assertFalse(tab.resume_selector.model().item(2).isEnabled())

    def test_stale_artifacts_do_not_enable_a_manifest_invalidated_stage(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            _manifest(root)
            (root / "nvt.gro").write_text(GRO_TEXT, encoding="utf-8")
            (root / "nvt.cpt").write_text("checkpoint", encoding="utf-8")
            tab = MDRunTab(
                runner_factory=lambda *args, **kwargs: FakeRunner(*args, **kwargs),
                capability_probe=lambda _exe, _env: _capabilities(),
                artifact_validators=_validators(),
            )
            self.addCleanup(tab.deleteLater)

            tab.load_project(str(root))

            self.assertEqual(
                tab.stage_widgets[StageName.NVT].status.text(),
                "Not ready",
            )
            self.assertFalse(tab.resume_selector.model().item(2).isEnabled())

            _set_stage_status(root, StageName.NVT, StageStatus.COMPLETED)
            tab.refresh_from_manifest()
            self.assertFalse(tab.resume_selector.model().item(2).isEnabled())

    def test_stage_status_and_gromacs_logs_are_reflected_in_the_ui(self):
        created = []

        def factory(manifest_file, stages, capabilities, *, resume=False):
            runner = FakeRunner(
                manifest_file,
                stages,
                capabilities,
                resume=resume,
            )
            created.append(runner)
            return runner

        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            _manifest(root)
            tab = MDRunTab(
                runner_factory=factory,
                capability_probe=lambda _exe, _env: _capabilities(),
                artifact_validators=_validators(),
            )
            self.addCleanup(tab.deleteLater)

            tab.load_project(str(root))
            tab.run_button.click()
            runner = created[0]
            runner.stage_changed.emit("nvt", "running", "NVT is running.")
            runner.log_line.emit("Step 2500  Time 5.000")
            runner.finished_with_status.emit(True, "done")

            self.assertEqual(tab.stage_widgets[StageName.NVT].status.text(), "Running")
            self.assertIn("[GROMACS] Step 2500  Time 5.000", tab.log.toPlainText())
            self.assertIn("[MolDynStudio] done", tab.log.toPlainText())

    def test_stop_button_delegates_to_active_runner(self):
        created = []

        def factory(manifest_file, stages, capabilities, *, resume=False):
            runner = FakeRunner(
                manifest_file,
                stages,
                capabilities,
                resume=resume,
            )
            created.append(runner)
            return runner

        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            _manifest(root)
            tab = MDRunTab(
                runner_factory=factory,
                capability_probe=lambda _exe, _env: _capabilities(),
                artifact_validators=_validators(),
            )
            self.addCleanup(tab.deleteLater)

            tab.load_project(str(root))
            tab.run_button.click()
            tab.stop_button.click()

            self.assertTrue(created[0].stopped)

    def test_resume_checkpoint_starts_only_production_and_locks_controls(self):
        created = []

        def factory(manifest_file, stages, capabilities, *, resume=False):
            runner = FakeRunner(
                manifest_file,
                stages,
                capabilities,
                resume=resume,
            )
            created.append(runner)
            return runner

        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            _manifest(root)
            (root / "md.tpr").write_text("tpr", encoding="utf-8")
            (root / "md.cpt").write_text("checkpoint", encoding="utf-8")
            _set_stage_status(root, StageName.PRODUCTION, StageStatus.INTERRUPTED)
            tab = MDRunTab(
                runner_factory=factory,
                capability_probe=lambda _exe, _env: _capabilities(),
                artifact_validators=_validators(),
            )
            self.addCleanup(tab.deleteLater)
            tab.load_project(str(root))

            tab.resume_selector.setCurrentIndex(4)
            tab.resume_button.click()

            self.assertEqual(len(created), 1)
            self.assertTrue(created[0].started)
            self.assertTrue(created[0].resume)
            self.assertEqual(
                [stage.name for stage in created[0].stages],
                [StageName.PRODUCTION],
            )
            self.assertFalse(tab.run_button.isEnabled())
            self.assertFalse(tab.resume_selector.isEnabled())
            self.assertFalse(tab.resume_button.isEnabled())
            self.assertTrue(tab.stop_button.isEnabled())

    def test_refresh_during_active_run_preserves_context_and_recovers_controls(self):
        created = []

        def factory(manifest_file, stages, capabilities, *, resume=False):
            runner = FakeRunner(
                manifest_file,
                stages,
                capabilities,
                resume=resume,
            )
            created.append(runner)
            return runner

        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            _manifest(root)
            tab = MDRunTab(
                runner_factory=factory,
                capability_probe=lambda _exe, _env: _capabilities(),
                artifact_validators=_validators(),
            )
            self.addCleanup(tab.deleteLater)
            tab.load_project(str(root))
            tab.run_button.click()

            tab.load_project(str(root))
            created[0].finished_with_status.emit(True, "done")

            self.assertTrue(tab.run_button.isEnabled())
            self.assertTrue(tab.resume_selector.isEnabled())

    def test_plots_remain_empty_until_real_parser_values_arrive(self):
        created = []

        def factory(manifest_file, stages, capabilities, *, resume=False):
            runner = FakeRunner(
                manifest_file,
                stages,
                capabilities,
                resume=resume,
            )
            created.append(runner)
            return runner

        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            _manifest(root)
            tab = MDRunTab(
                runner_factory=factory,
                capability_probe=lambda _exe, _env: _capabilities(),
                artifact_validators=_validators(),
            )
            self.addCleanup(tab.deleteLater)
            tab.load_project(str(root))

            empty_labels = [
                label
                for label in tab.findChildren(QLabel)
                if label.text() == "No live data yet"
            ]
            self.assertEqual(len(empty_labels), 3)
            self.assertTrue(all(not label.isHidden() for label in empty_labels))

            tab.run_button.click()
            runner = created[0]
            runner.stage_changed.emit("minimization", "running", "running")
            runner.log_line.emit("           Step           Time")
            runner.log_line.emit("           2500        5.00000")
            runner.log_line.emit("Temperature  =  300.15")

            temperature_empty = next(
                label
                for label in empty_labels
                if label.accessibleName() == "Temperature plot empty state"
            )
            pressure_empty = next(
                label
                for label in empty_labels
                if label.accessibleName() == "Pressure plot empty state"
            )
            self.assertTrue(temperature_empty.isHidden())
            self.assertFalse(pressure_empty.isHidden())

    def test_md_run_has_no_mock_execution_attributes(self):
        tab = MDRunTab()
        self.addCleanup(tab.deleteLater)

        for attribute in ("_timer", "_sample", "start_mock_run", "_tick"):
            self.assertFalse(hasattr(tab, attribute))


if __name__ == "__main__":
    unittest.main()
